[project]
name = "mine-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "apis-acdhch-default-settings>=2.20.0",
    "apis-acdhch-django-invite>=0.2.0",
    "apis-core-rdf>=0.65.1",
    "django-compressor>=4.6.0",
    "django-interval>=0.5.2",
    "django-json-editor-field>=0.4.2",
    "django-sass-processor>=1.4.2",
    "imgproxy>=1.0.0",
    "psycopg[binary]>=3.3.4",
]

[dependency-groups]
dev = [
    "djlint==1.36.4",
    "ruff>=0.16.0,<0.17.0",
    "deptry>=0.12,<0.25",
    "debugpy>=1.8.21",
    "django-extensions>=4.1",
]

[tool.djlint]
indent=2
profile="django"
extension="html"
blank_line_before_tag="block"
blank_line_after_tag="endblock"
format_js=false

[tool.ruff]
lint.select = ["E4", "E7", "E9", "F", "I"]
lint.ignore = ["E501", "F403"]
lint.isort.known-first-party = ["apis_core"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["apis_ontology"]
