# Generated by Django 5.1.6 on 2025-08-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="anhaengervon",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ausbildungan",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="autorvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="beruf",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ehepartnervon",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ehrentitelvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ehrentitelvoninstitution",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ereignis",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="erwaehntin",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="fach",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="familienmitgliedvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="findetstattin",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="freundvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="geborenin",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="gelegenin",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="gelegeninort",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="gestorbenin",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="gewinnt",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="haeltredebei",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="institution",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="institutionhierarchie",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="kindvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="lehntpreisab",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="lehrervon",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="mitglied",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="nichtgewaehlt",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="nimmtteilan",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="oeawmitgliedschaft",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="ort",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="person",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="positionan",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="preis",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="religion",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="schreibtaus",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="stelltantragan",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="stiftet",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="versionanhaengervon",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionausbildungan",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionautorvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionehepartnervon",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionehrentitelvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionehrentitelvoninstitution",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionereignis",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionerwaehntin",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionfach",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionfamilienmitgliedvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionfindetstattin",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionfreundvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versiongeborenin",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versiongelegenin",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versiongelegeninort",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versiongestorbenin",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versiongewinnt",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionhaeltredebei",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versioninstitution",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versioninstitutionhierarchie",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionkindvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionlehntpreisab",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionlehrervon",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionmitglied",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionnichtgewaehlt",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionnimmtteilan",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionoeawmitgliedschaft",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionort",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionperson",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionpositionan",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionpreis",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionreligion",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionschreibtaus",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionstelltantragan",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionstiftet",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwerk",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwirdgestiftetvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwirdvergebenvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="versionwissenschaftsaustauschin",
            name="old_id",
            field=models.IntegerField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="werk",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="wirdgestiftetvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="wirdvergebenvon",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="wissenschaftsaustauschin",
            name="old_id",
            field=models.IntegerField(
                blank=True, editable=False, null=True, unique=True
            ),
        ),
    ]
