# Generated by Django 5.1.6 on 2025-08-14 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0002_alter_anhaengervon_old_id_alter_ausbildungan_old_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ausbildungan",
            name="typ",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Schule", "Schule"),
                    ("Studium", "Studium"),
                    ("Promotion", "Promotion"),
                    ("Habilitation", "Habilitation"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="versionausbildungan",
            name="typ",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Schule", "Schule"),
                    ("Studium", "Studium"),
                    ("Promotion", "Promotion"),
                    ("Habilitation", "Habilitation"),
                ],
                max_length=255,
            ),
        ),
    ]
