# Generated by Django 5.1.6 on 2025-08-08 07:02

import apis_core.generic.abc
import django.db.models.deletion
import django_json_editor_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis_ontology', '0003_beruf_old_id_alter_beruf_name_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='alternative_namen',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ort',
            name='alternative_namen',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='alternative_namen',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versioninstitution',
            name='alternative_namen',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versionort',
            name='alternative_namen',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versionperson',
            name='alternative_namen',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='versionwerk',
            name='alternative_namen',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='werk',
            name='alternative_namen',
            field=django_json_editor_field.fields.JSONEditorField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Bild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('OEAW Archiv', 'OEAW Archiv'), ('Wikimedia', 'Wikimedia')], max_length=100)),
                ('pfad', models.CharField(max_length=1024)),
                ('credit', models.TextField(blank=True, max_length=1024)),
                ('object_id', models.PositiveBigIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Bild',
                'verbose_name_plural': 'Bilder',
            },
            bases=(apis_core.generic.abc.GenericModel, models.Model),
        ),
    ]
