# Generated by Django 5.1.6 on 2025-08-22 12:52

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0003_alter_ausbildungan_typ_alter_versionausbildungan_typ"),
    ]

    operations = [UnaccentExtension()]
