# Generated by Django 5.1.6 on 2025-09-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apis_ontology", "0004_auto_20250822_1252"),
    ]

    operations = [
        migrations.AddField(
            model_name="erwaehntin",
            name="typ",
            field=models.CharField(
                blank=True,
                choices=[("erwähnt", "erwähnt"), ("behandelt", "behandelt")],
                default="erwähnt",
                help_text="Art der Erwähnung",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="versionerwaehntin",
            name="typ",
            field=models.CharField(
                blank=True,
                choices=[("erwähnt", "erwähnt"), ("behandelt", "behandelt")],
                default="erwähnt",
                help_text="Art der Erwähnung",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="versionwerk",
            name="typ",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Buch", "Buch"),
                    ("Zeitschrift", "Zeitschrift"),
                    ("Zeitschriftenartikel", "Zeitschriftenartikel"),
                    ("Monographie", "Monographie"),
                    ("Konferenzband", "Konferenzband"),
                    ("Konferenzbeitrag", "Konferenzbeitrag"),
                    ("Dissertation", "Dissertation"),
                    ("Habilitation", "Habilitation"),
                    ("Patent", "Patent"),
                    ("Nekrolog", "Nekrolog"),
                    ("Sonstiges", "Sonstiges"),
                ],
                default="Sonstiges",
                help_text="Art des Werks",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="werk",
            name="typ",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Buch", "Buch"),
                    ("Zeitschrift", "Zeitschrift"),
                    ("Zeitschriftenartikel", "Zeitschriftenartikel"),
                    ("Monographie", "Monographie"),
                    ("Konferenzband", "Konferenzband"),
                    ("Konferenzbeitrag", "Konferenzbeitrag"),
                    ("Dissertation", "Dissertation"),
                    ("Habilitation", "Habilitation"),
                    ("Patent", "Patent"),
                    ("Nekrolog", "Nekrolog"),
                    ("Sonstiges", "Sonstiges"),
                ],
                default="Sonstiges",
                help_text="Art des Werks",
                max_length=100,
            ),
        ),
    ]
