# Generated by Django 5.2.7 on 2025-11-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0005_erwaehntin_typ_versionerwaehntin_typ_versionwerk_typ_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ort",
            name="feature_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='<a href="https://www.geonames.org/export/codes.html" target="_blank">Geonames Feature Code List</a>',
                max_length=16,
                verbose_name="feature code",
            ),
        ),
        migrations.AlterField(
            model_name="versionort",
            name="feature_code",
            field=models.CharField(
                blank=True,
                default="",
                help_text='<a href="https://www.geonames.org/export/codes.html" target="_blank">Geonames Feature Code List</a>',
                max_length=16,
                verbose_name="feature code",
            ),
        ),
    ]
