# Generated by Django 5.2.7 on 2026-01-30 13:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "apis_ontology",
            "0007_alter_institution_typ_alter_positionan_position_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="typ",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kommission", "Kommission"),
                    ("Institut", "Institut"),
                    ("Forschungsstelle", "Forschungsstelle"),
                    ("Klasse", "Klasse"),
                    ("Verwaltung", "Verwaltung"),
                    (
                        "Wissenschaftsorientierte Einheit",
                        "Wissenschaftsorientierte Einheit",
                    ),
                    ("Einrichtung", "Einrichtung"),
                    ("Komitee", "Komitee"),
                    ("Kuratorium", "Kuratorium"),
                    ("Beirat", "Beirat"),
                    ("Delegation", "Delegation"),
                    (
                        "Internationales Forschungsprogramm",
                        "Internationales Forschungsprogramm",
                    ),
                    ("Preis", "Preis"),
                    ("Ministerium", "Ministerium"),
                    ("Orden (geistl.)", "Orden (geistl.)"),
                    ("Schule", "Schule"),
                    ("Kirche", "Kirche"),
                    ("Gymnasium", "Gymnasium"),
                    ("Akademie (Ausland)", "Akademie (Ausland)"),
                    ("Universität", "Universität"),
                    ("Ministerium", "Ministerium"),
                ],
                default="unbekannt",
                help_text="Art der Institution",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="versioninstitution",
            name="typ",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Kommission", "Kommission"),
                    ("Institut", "Institut"),
                    ("Forschungsstelle", "Forschungsstelle"),
                    ("Klasse", "Klasse"),
                    ("Verwaltung", "Verwaltung"),
                    (
                        "Wissenschaftsorientierte Einheit",
                        "Wissenschaftsorientierte Einheit",
                    ),
                    ("Einrichtung", "Einrichtung"),
                    ("Komitee", "Komitee"),
                    ("Kuratorium", "Kuratorium"),
                    ("Beirat", "Beirat"),
                    ("Delegation", "Delegation"),
                    (
                        "Internationales Forschungsprogramm",
                        "Internationales Forschungsprogramm",
                    ),
                    ("Preis", "Preis"),
                    ("Ministerium", "Ministerium"),
                    ("Orden (geistl.)", "Orden (geistl.)"),
                    ("Schule", "Schule"),
                    ("Kirche", "Kirche"),
                    ("Gymnasium", "Gymnasium"),
                    ("Akademie (Ausland)", "Akademie (Ausland)"),
                    ("Universität", "Universität"),
                    ("Ministerium", "Ministerium"),
                ],
                default="unbekannt",
                help_text="Art der Institution",
                max_length=100,
            ),
        ),
    ]
