# Positionen im Präsidium
POSITIONEN_PRES = [
    "Präsident(in)",
    "Vizepräsident(in)",
    "Generalsekretär(in)",
    "Sekretär(in)",
    "Präsident(in) Klasse",
    "Sekretär(in) Klasse",
]

POSITIONEN = [
    "Kustos-Adjunkt(in)",
    "Geolog(e/in)",
    "Kustos/Kustodin",
    "Generalkonsul(in)",
    "Consulting Physicist",
    "Gaudozentenführer(in)",
    "Sekretär(in) Klasse",
    "Staatskonservator(in)",
    "Amanuensis",
    "Unterstaatssekretär(in)",
    "wissenschaftliche(r) Direktor(in)",
    "Direktor(in)",
    "Referent(in)",
    "Direktor(in) (Institut/Forschungstelle)",
    "Obmann/Obfrau-Stellvertreter(in)",
    "Demonstrator(in)",
    "Landeshistoriograph(in)",
    "tit. Staatsarchivar(in)",
    "Ehrensenator(in)",
    "stv. interimistischer Leiter",
    "Gastprofessor(in)",
    "Generaldirektor(in)",
    "Prosektor-Adjunkt(in)",
    "Landesarchivar-Aspirant(in)",
    "Kuratorium",
    "Aspirant(in)",
    "Mitbegründer(in)",
    "Kustos/Kustodin 1. Klasse",
    "Chefarzt/ärztin",
    "Vertretungsprofessor(in)",
    "k.k. Appellationsgerichtsrat/-rätin",
    "Prorektor(in)",
    "Sekretär(in)",
    "Assistent(in)",
    "Oberlandesgerichtsrat(rätin)",
    "Hofdolmetscher(in)",
    "k.k. Reichshistoriograph(in)",
    "k.k. Appellationssektretär(in)",
    "Unter-Staatsarachivar(in)",
    "Profektor(in)",
    "Ehrenkurator(in)",
    "Bibliothekar(in)",
    "Konsulant(in)",
    "Abgeordnete(r)",
    "Volontär(in)",
    "Konsiliari(n/us)",
    "Erste(r) Astronom(in)",
    "Vorstand/Vorständin",
    "o. Univ.-Prof.",
    "wissenschaftliche Hilfskraft",
    "Vorsitzende(r)",
    "hat Position inne",
    "Chefgeolog(e/in)",
    "stv. Leiter(in)",
    "Ehrenbürger(in)",
    "Prodekan(in)",
    "Kustos-Adjunkt(in) 4. Klasse",
    "Prosektor(in)",
    "Minister(in)",
    "Internuntius",
    "leitet",
    "Oberbibliothekar(in)",
    "Generalstaatsbibliothekar(in)",
    "Präsident(in) Klasse",
    "Erste(r) Direktor(in)",
    "Konservator(in)",
    "Generalstaatsarchivar(in)",
    "Intendant(in)",
    "Skriptor(in)",
    "durch Akklamation bestellt",
    "Dekan(in)",
    "Kuratorstellvertreter",
    "wissenschaftliche(r) Mitarbeiter(in)",
    "Archivar(in)",
    "Abteilungsdirektor(in)",
    "Mitarbeiter(in)",
    "Hospitant(in)",
    "Honorar-Prof.",
    "Abteilungsleiter(in)",
    "Ministerialsekretär(in)",
    "Kustos/Kustodin 2. Klasse",
    "Vizepräsident(in)",
    "Präfekt(in)",
    "Konzipist(in)",
    "technische(r) Hilfsarbeiter(in)",
    "Abt/Äbtissin",
    "Adjunkt(in)",
    "Senator(in)",
    "Kommissionsmitglied",
    "Oberarchivar(in)",
    "Institutsdirektor(in)",
    "Obmann/Obfrau (Kommission)",
    "Rektor(in)",
    "tit. o. Univ.-Prof.",
    "Priv.-Doz.",
    "Beamte(r)",
    "Advisory Board",
    "Chef-Astronom(in)",
    "Generalsekretär(in)",
    "interimistischer Leiter",
    "Supplent(in)",
    "Kurator",
    "Delegierte(r)",
    "Korrespondent(in)",
    "Ingenieur(in)",
    "Observator(in)",
    "Präsidialgesandte(r)",
    "Sektionsrat/-rätin",
    "Mitdirektor(in)",
    "Praktikant(in)",
    "Kustos-Adjunkt(in) 1. Klasse",
    "Landeskonservator(in)",
    "ao. Univ.-Prof.",
    "Sektionschef(in)",
    "Astronom(in)",
    "Konzeptspraktikant(in)",
    "tit. Univ.-Prof.",
    "Kustos-Adjunkt(in) 2. Klasse",
    "tit. ao. Univ.-Prof.",
    "Leiter(in)",
    "Kustos-Adjunkt(in) 3. Klasse",
    "kommissarische(r) Leiter(in)",
    "stv. Direktor(in)",
    "Ministerialrat/-rätin",
    "Landesarchivar(in)",
    "Staatsarchivar(in)",
    "kommissarische(r) Lehrstuhlinhaber(in)",
    "Univ.-Doz.",
    "außerordentlicher Gesandter und bevollmächtigter Minister am",
    "Präsident(in)",
    "Sammlungsleiter(in)",
    "apl. Univ.-Prof.",
    "Vorsitzende(r)",
    "1. Stellvertreter(in)",
    "2. Stellvertreter(in)",
]
